### ISSUE TITLE
ngImgCrop not working in ngDialog popup.

### ISSUE THREAD

**Issue by smrutiranjan727** [alexk111/ngImgCrop#135]
@alexk111  I'm using mvc and angularjs for my project. When I use this plugin in a simple page it works, but the problem occurs when I try to use the plugin in an ngDialog popup. I don't think the plug in is supported to be used in an ngDialog popup. Is there any work around for this issue?

Thank You!!!

**Comment by smrutiranjan727** [comment]
Solved the issue by just adding a timeout function like,
`$timeout(function() {
angular.element(document.querySelector('#fileInput')).on('change', handleFileSelect);
},1000, false);`

**Comment by chhumsina** [comment]
Dear Bro @smrutiranjan727 ,

Could I have a full source code of popup with crop image.

Many thank  :)
