### ISSUE TITLE
The repository was abandoned?

### ISSUE THREAD

**Issue by rayronvictor** [alexk111/ngImgCrop#138]
No pull request accepted since 2014. What's going on?
The npm release still in 0.2.0 version.

**Comment by xileftenurb** [comment]
there is some fork of this repository who are still active.
I found these two :
https://github.com/CrackerakiUA/ngImgCropFullExtended
https://github.com/vogloblinsky/ngImgCropExtended

one is a fork of the other, but there are both active.
I don't know the difference between them.

**Comment by rickerd** [comment]
The repo or CrackerakiUA is ahead of all forks.
Me and Denis implemented cool features and do most of the work on the amazing plugin.

I asked the owner to transfer the repo to me so i can develop it even better.
Give a +1 to help me with this task.
