### ISSUE TITLE
Upload image on IOS Iphone from camera

### ISSUE THREAD

**Issue by Anegustorov** [alexk111/ngImgCrop#154]
Can not upload image on iOS 9.3.3 when take picture from camera

**Comment by rdeslonde** [comment]
Having the same problem. But it doesn't work with camera or existing images.

**Comment by cgf150** [comment]
me too -_- , did you find any way to solve this problem?

**Comment by rickerd** [comment]
Use the better and maintained library https://github.com/CrackerakiUA/ngImgCropFullExtended

**Comment by Anegustorov** [comment]
Thank you so much rickerd, it's really help me!!!
