### ISSUE TITLE
result-image not working

### ISSUE THREAD

**Issue by TrkiSF2** [alexk111/ngImgCrop#18]
Is it from some reason possible please that when I move working code inside angular ui-bootstrap. The result image is not updating anymore on crop?

The code:

```
<img-crop image="myImage" area-type="square" result-image="myCroppedImage"></img-crop>
```

**Comment by GabiAxel** [comment]
UI's modal scope messes with the img-crop directive's scope. In updateResultImage() there is a check for if(angular.isDefined(scope.resultImage)) and it is false. I overcame this by opening the modal with a scope that contains "resultImage" (value doesn't matter, as long as it's defined) like this:

```javascript
$modal.open({
   scope: angular.extend($rootScope.$new(), {
      resultImage: ''
   })
});
```

**Comment by asheshambasta** [comment]
All that is a workaround yes. But to have it not work with something as standard as UI is an alarm bell. 


We already switched to jQuery's cropper and wrote a custom directive around it which works really well. In any production situation, these workarounds can give me sleepless nights. 


—
Best,

Ashesh Ambasta

**Comment by rocketmannot** [comment]
I have the same problem even with:
```javascript
$modal.open({
   scope: angular.extend($rootScope.$new(), {
      resultImage: ''
   })
});
```
I just can not understand why bidirectional bind variable: ```result-image``` is not updated inside my controller. Inside ```updateResultImage()``` is updated. But the value of my corresponding variable in controller is not. I tryed to use callback ```onChange```. The call back is called but instead of result image i get ```undefinde```. Futher more i tryed to define my own call back on the directive ```imgCrop``` and pass the value of the result image inside it. How ever the result is the same - the call back called but i get ```undefined``` as argument. Sorry i acn not reproduce this problem. This problem is reproduced only in my development env.

**Comment by adriantadros** [comment]
I have the exact same problem described by rocketmannot. Has anyone managed to resolve this?

**Comment by adriantadros** [comment]
Update: I managed to resolve this by setting change-on-fly="true".

See below:

```
<img-crop
   image="imageData"
   result-image="croppedImage"
   area-type="square"
   result-image-format="image/png"
   result-image-size="60"
   result-image-quality="0.6"
   change-on-fly="true"></img-crop>
```

**Comment by coommark** [comment]
Yo @asheshambasta! Can you share the directive or a little sample of the one you did with Cropper? Pls

**Comment by adriantadros** [comment]
Actually what solved it for me was making sure image and result-image were not set directly on the $scope object.

So instead of:
```
$scope.image = '';
$scope.croppedImage = '';
```

I used:
```
$scope.image = {
   originalImage: '',
   croppedImage: ''
};
```

Then updated my directive to:
```
<img-crop
   image="image.originalImage"
   result-image="image.croppedImage"></img-crop>
```

And that seemed to resolve the problem. I think it is something to do with the way angular treats string values assigned to $scope by value rather than by reference.

**Comment by santhoshses** [comment]
@alexk111  i want to disable the  resize property of the croping tool. actually i need a  fixed width and height for the croper.Please help me out on this.

**Comment by leob** [comment]
@adriantadros Excellent!!!

I had the same issue, the solution is simple and works flawlessly, this should be mentioned in the documentation (README).

**Comment by ortho23** [comment]
@adriantadros comment worked for me, thanks!

**Comment by santanu123456** [comment]
In my project I am using  ng-img-crop. It works fine. But when I tried to run in production, it is not behaving properly. 
On selecting the same image, the pages were behaving differently.
Snapshot of the page which is working fine:
![developermode](https://cloud.githubusercontent.com/assets/15865576/11925897/ed041412-a7e5-11e5-90b2-e8e4cc3649c8.png)

Snapshot of the page from production site:
![warfile](https://cloud.githubusercontent.com/assets/15865576/11925937/45a5c91c-a7e6-11e5-9dee-b35921b74b2f.png)
the difference I found by inspecting both the pages(in chromium browser) is that the canvas that is under the img-crop,  is taking margin-top and margin-left by it self along with that width and height.

please help to solve this issue. Thanks in advance

**Comment by txtbits** [comment]
@adriantadros Solved. Simple solution. Thank you!

**Comment by lechengyu** [comment]
@adriantadros It really helps! Thank you!

**Comment by ldwonday** [comment]
@lechengyu Can you paste the full code?

**Comment by anaganisk** [comment]
@alexk111 the solution by @adriantadros works, may be it would be great if you add it in documentation

**Comment by anaganisk** [comment]
here is what I did in case anyone needs a cleaner solution without any workarounds
`angular.module('poch').directive('addprofile',function(){
    return{
        restrict: 'E',
        templateUrl: 'client/modules/add-profile-details/add-profile.html',
        controllerAs: 'addProfileController',
        controller: function($scope,$reactive){
            var vm = this;
            $reactive(this).attach($scope);
            this.helpers({
                imgSrc: function(){
                  return undefined;
                },
                image: function(){
                    return {
                        originalImage: undefined,
                        croppedImage: undefined
                    };
                }
            });
            this.addAvatar = function(files){
                if (files.length > 0) {
                    var reader = new FileReader();
                    reader.onload = function(e){
                        $scope.$apply(function(){
                            vm.image.originalImage = e.target.result;
                        });
                    };
                    reader.readAsDataURL(files[0]);
                }
                else {
                    this.image.originalImage = undefined;
                }
            };
            this.saveAvatar = function(){
                this.imgSrc = this.image.croppedImage;
                this.image.originalImage = undefined;
            }
        }
    }
});`

**Comment by anaganisk** [comment]
here is what I did in case anyone needs a cleaner solution without any workarounds

````
angular.module('poch').directive('addprofile',function(){
return{
        restrict: 'E',
        templateUrl: 'client/modules/add-profile-details/add-profile.html',
        controllerAs: 'addProfileController',
        controller: function($scope,$reactive){
            var vm = this;
            $reactive(this).attach($scope);
            this.helpers({
                imgSrc: function(){
                  return undefined;
                },
                image: function(){
                    return {
                        originalImage: undefined,
                        croppedImage: undefined
                    };
                }
            });
            this.addAvatar = function(files){
                if (files.length > 0) {
                    var reader = new FileReader();
                    reader.onload = function(e){
                        $scope.$apply(function(){
                            vm.image.originalImage = e.target.result;
                        });
                    };
                    reader.readAsDataURL(files[0]);
                }
                else {
                    this.image.originalImage = undefined;
                }
            };
            this.saveAvatar = function(){
                this.imgSrc = this.image.croppedImage;
                //Avatar.insert(this.image.croppedImage, function (err, fileObj) {
                //});
                this.image.originalImage = undefined;
            }
        }
    }
});
````

**Comment by bitf09a013** [comment]
@adriantadros Thank you mate!

**Comment by darkmedia** [comment]
@adriantadros Thank you man, it work for me!.

**Comment by kabrice** [comment]
Nothing is working for me :(

**Comment by ignj** [comment]
@kabrice try [this](http://jsfiddle.net/danialfarid/xxo3sk41/590/) (forget the part of ngFileUpload)

**Comment by lahong** [comment]
@ignj thanks for posting the fiddle awesome stuff,can you please post and example sending the image with form field aswell
