### ISSUE TITLE
CORS question

### ISSUE THREAD

**Issue by jaesung2061** [alexk111/ngImgCrop#37]
How can I allow images from other sites to be shown?

**Comment by rodrigoreis22** [comment]
I'm having the same issue when I try to show the current image on the canvas. It worked before.

**Comment by nchudleigh** [comment]
Having the same issue, I believe you can set cross origin attributes on the canvas element?

https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

going to try out some changes and if they work ill make a pull request for a CORSenabled option.

**Comment by nchudleigh** [comment]
![screen shot 2015-02-22 at 11 58 15 pm](https://cloud.githubusercontent.com/assets/5580824/6322991/07bbe9b8-baef-11e4-9533-679ea4770a32.png)

**Comment by PR-O** [comment]
Hi @nchudleigh , did you ever get this working? We've run into the same wall :(.

**Comment by nchudleigh** [comment]
I am sorry to say that no I didn't find a fix.  Though if I do I will come back and post the solution.  I fear it may be more complicated than I thought.  Might take some hacky fixes but I will be forced to figure it out in the next few weeks.  Stay tuned.

**Comment by PR-O** [comment]
We were trying to load the original image (image="" property) from our S3 bucket, without having any Cross Origin settings on the bucket. We ended up configuring Cross Origin settings:

http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html

Now it all works.
