### ISSUE TITLE
Uploading Coupled with Image Crop

### ISSUE THREAD

**Issue by brianfeister** [alexk111/ngImgCrop#39]
This is not a "bug", I just wanted to offer some advice to other developers solving this common use case of uploading and cropping images. For the image crop piece, this library does far better than any others I've found - so thank you for this! The other piece of the puzzle, is a library that handles file uploads really well and can work in harmony with `ngImgCrop`.  The `angular-file-upload` library is here (not to be confused with the inferior library of the same name): https://github.com/nervgh/angular-file-upload/ and you can find discussion of the integration here: https://github.com/nervgh/angular-file-upload/issues/208#issuecomment-67981024

And I've created a gist that demonstrates wiring all the pieces together over here:  https://gist.github.com/brianfeister/56a1c6c77cd5928a1c53

**Comment by xeroxoid** [comment]
Just a question. Why do you consider https://github.com/danialfarid/angular-file-upload an inferior library?

**Comment by brianfeister** [comment]
Poor documentation and a number of "black box" factors that aren't well explained.

**Comment by xeroxoid** [comment]
Don't mean to start a flame war here and I am in no way affiliated with danialfarid, but I tend to disagree about the documentation part... On the main md file the documentation is solid, with many examples and all options inlined and commented (which is not the case in nervgh's library) and the man even has examples for most major backend architectures... Oh and way more recent updates, stars, less pull req's etc..

**Comment by brianfeister** [comment]
No problem, the parts that I needed were less documented so we had a different experience.

**Comment by xeroxoid** [comment]
Cool, and thanks for the gist!

**Comment by ikantthink** [comment]
If you don't care about supporting old browsers you could create a simple upload service using FormData. Have a read here: 
http://uncorkedstudios.com/blog/multipartformdata-file-upload-with-angularjs
angular-file-upload is a great tool, but I found it to be too much for just an avatar upload.

On the server side multer is a slick way to go. Assuming you're using node/express...
https://github.com/expressjs/multer

**Comment by FURQAN2050** [comment]
can you come on skype to solve ?

**Comment by FURQAN2050** [comment]
am too much tired too solve this issue,
