### ISSUE TITLE
Could not load image data

### ISSUE THREAD

**Issue by aecepoglu** [alexk111/ngImgCrop#64]
In the fiddle below, I'm trying to get an image by supplying in the image URL.
With some images however, I'm getting errors.

It will say that in the Network inspection section of Firefox that it "Could not load the image"

https://jsfiddle.net/rw6q9/699/

This URL instead works fine: http://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Nina_Persson_Stockholm_Pride_Festival_2009_1.jpg/600px-Nina_Persson_Stockholm_Pride_Festival_2009_1.jpg

I realized that the 2nd one had an **Allow Origin: "*"** in its response headers. But I don't know if that matters at all

**Comment by Younderboy** [comment]
I'm having the same issue :-)

**Comment by PR-O** [comment]
See #37 .

**Comment by s875515** [comment]
hmmmmm.... http:// change to https://  can fix this problem

**Comment by aecepoglu** [comment]
I no longer use this
