### ISSUE TITLE
UI Modal

### ISSUE THREAD

**Issue by tommykennedy** [alexk111/ngImgCrop#77]
Hi,

I am trying to use the directive inside a Modal however the handlefileselect function does not seem to get called in the modal controller. 

I presume its because of the angular.element not properly registering the function due to the DOM not being loaded. I have tried to add a timeout and no luck. 

Any suggestions greatly appreciated?

    .controller('ProfilePictureModalInstanceCtrl', function ($scope, $modalInstance, items,$timeout) {

    $scope.myImage = '';
    $scope.myCroppedImage = '';

    var handleFileSelect = function (evt) {

        alert("Here");

        var file = evt.currentTarget.files[0];
        var reader = new FileReader();
        reader.onload = function (evt) {
            $scope.$apply(function ($scope) {
                $scope.myImage = evt.target.result;
            });
        }
        reader.readAsDataURL(file);
    }

    angular.element(document.querySelector('#fileInput')).on('change', handleFileSelect);

    $scope.ok = function () {
        $modalInstance.close($scope.optionItems);
    };

    $scope.cancel = function () {
        $modalInstance.dismiss('cancel');
    };
    });

The HTML for the modal is 

    <script type="text/ng-template" id="profilePictureModal.html">
        <div class="modal-header">
            <h3 class="modal-title">Upload Profile Picture</h3>
        </div>
        <div class="modal-body">

            <div class="row">
                <div class="cropArea col-md-6">
                    <div class="row">
                        <div>Profile Picture</div>
                    </div>
                    <div class="row">
                        <div>
                            <img-crop image="myImage" result-image="myCroppedImage"></img-crop>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">Thumbnail:</div>
                <div><img ng-src="{{myCroppedImage}}" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">Select Profile Picture:
                    <input type="file" id="fileInput" />
                </div>
            </div>

        </div>
        <div class="modal-footer">
            <button class="btn btn-primary" ng-click="ok()">OK</button>
            <button class="btn btn-warning" ng-click="cancel()">Cancel</button>
        </div>
    </script>

**Comment by tommykennedy** [comment]
I solved this by adding the following directive

.directive('customOnChange', function () {
    return {
        restrict: 'A',
        link: function (scope, element, attrs) {
            var onChangeHandler = scope.$eval(attrs.customOnChange);
            element.bind('change', onChangeHandler);
        }
    };
})

and then I define the function in the controller

    $scope.uploadFile = function (event) {

        var file = event.currentTarget.files[0];
        var reader = new FileReader();
        reader.onload = function (event) {
            $scope.$apply(function ($scope) {
                $scope.myImage = event.target.result;
                //console.log($scope.myImage);
            });
        }
        reader.readAsDataURL(file);

    };

and it gets set to the HTML like so

            <div>Select an image file:
                <input type="file" id="fileInput" custom-on-change="uploadFile" />
            </div>
            <div class="cropArea">
                <img-crop image="myImage" result-image="myCroppedImage"></img-crop>
            </div>
            <div>Cropped Image:</div>
            <div><img ng-src="{{myCroppedImage}}" />
            </div>

**Comment by c0debreaker** [comment]
I'm going to try your code later. I have this code inside the controller for my modalinstance and it's weird that it doesn't get called. I can see the myCroppedImage image on the browser gets updated correctly though but it doesn't update $scope.myCroppedImage

```
    $scope.$watch('myCroppedImage', function(newValue, oldValue) {
    	console.log('myCroppedImage on ImageToThumbnailController', newValue, oldValue);
      	DataURIStorage.storeDataUri(newValue);
    });
```

I'll keep you posted.

**Comment by c0debreaker** [comment]
Actually, my issue is different. The issue is that inside my modal, the $scope.myCroppedImage doesn't get called. I am not sure why. I've already spent 8 hours debugging and I still can't figure it out. Any ideas?

**Comment by c0debreaker** [comment]
I fixed my issue by using dotted notation

**Comment by c0debreaker** [comment]
@yeremiapinggi I couldn't remember anymore but I'm sure I got it work a long time ago. Thanks.
