### ISSUE TITLE
Low quality result image. Setting result-image-quality does nothing.

### ISSUE THREAD

**Issue by 412andrewmortimer** [alexk111/ngImgCrop#86]
My result image is by default a low resolution and I can't not change it.

**Comment by bleriotusa** [comment]
You may need to play around with result-image-size as well. Possibly setting it to original photo size by using original-data.

**Comment by 412andrewmortimer** [comment]
I was passing the image around wrong. The image gets converted to a data:uri several times. So watch out for that.

**Comment by beebun** [comment]
@412andrewmortimer 
Can you explain more how you solved it?
I'm trying to get result image with normal resolution (compare to original image). But what I got right now is low resolution result image.
